<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalCaptions.Core\UniversalCaptions.Core.csproj" />
    <ProjectReference Include="..\UniversalCaptions.Speech\UniversalCaptions.Speech.csproj" />
    <ProjectReference Include="..\UniversalCaptions.Translation\UniversalCaptions.Translation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
